### ISSUE TITLE
Check type of file uploaded for project image

### ISSUE THREAD

**Issue by nivedita2015** [VeloCloud/website-ui#38]
Right now any type of file can be uploaded on project image. Fix that to only take images.

**Comment by bsherrill480** [comment]
Easiest fix: is to use the accept arribute, but not supported in all browsers
http://caniuse.com/#feat=input-file-accept

Done: https://github.com/VeloCloud/website-ui/commit/c8a2ab7b427acd9c7a2fa81f85a5cac4c24f07d5

**Comment by nivedita2015** [comment]
This is pretty cool! Thanks 👍
