### ISSUE TITLE
Forget Password Functionality

### ISSUE THREAD

**Issue by shivachaturvedi** [VeloCloud/website-ui#39]
A forget password functionality could be useful

**Comment by himi1** [comment]
forgot password sends a confirmation code. 
## Forgot password
curl -X POST https://12apa0a3pl.execute-api.us-east-1.amazonaws.com/dev/users/himanshi1/forgotpassword

then confirm password page, allows you to change the password, if and only if the confirmation code is input correctly
## Confirm forgot password
curl -X POST https://12apa0a3pl.execute-api.us-east-1.amazonaws.com/dev/users/confirmforgotpassword -d ‘{“username”: “himanshi1", “password”: “password”, “confirmationCode”: “968378"}’
