### ISSUE TITLE
After logging out, go to a restricted page, first show the content then go back to login page

### ISSUE THREAD

**Issue by kz4** [VeloCloud/website-ui#41]
This probably applies to many pages.

For example, log in as a user, go to team, record the URL. Log out, and go back to the recorded URL, first we see the team for like 0.1 second, then it gets directed back to login page.

In reality team page shouldn't even be shown though.

**Comment by chtran14** [comment]
For simplicity, as Ian mentioned on the other github issue post, he said after logging out an user will be redirected to the login page. Thus it has been reroute to that. Right now, we have many issues need to be taken care of, unless someone wants to do what you said above (which should be ideal) then we will leave the state as it is.
