### ISSUE TITLE
No team, but showing loading team message

### ISSUE THREAD

**Issue by kz4** [VeloCloud/website-ui#48]
I have no team, but it's showing this message
![image](https://cloud.githubusercontent.com/assets/15188104/25294347/b9c63b6a-26ac-11e7-977a-4a7a403fd8ff.png)

**Comment by jiachen9393** [comment]
I also found that. It should be api give back a 404 here. Need to change the loader to empty.

**Comment by kz4** [comment]
why should api give back 404? api is right, it's UI error message problem.

**Comment by chtran14** [comment]
Shiva and Sangeetha has been working toward this issue for a couple days. They will know how to fix it. Thanks

**Comment by chtran14** [comment]
I believed this has been fixed
