### ISSUE TITLE
Error in View dashboard

### ISSUE THREAD

**Issue by jiachen9393** [VeloCloud/website-ui#49]
## Description

(Add images if possible)
![image](https://cloud.githubusercontent.com/assets/19999647/25294656/38bbd2c6-26ae-11e7-94a8-2e3ef235162c.png)

## Steps to reproduce

error occurs using the button view dashboard in landscape page. But can access successfully from project page.

**Comment by nivedita2015** [comment]
tested with multiple landing pages and projects.It works. My guess is this was a one off error maybe because of dropping some projects at the database. Will keep an eye out for this during the end to end testing.

**Comment by nivedita2015** [comment]
Rechecking as mentioned by Tran that he saw this today.

**Comment by nivedita2015** [comment]
fixed passing params.projectId
