### ISSUE TITLE
New user's first name and last name is fixed

### ISSUE THREAD

**Issue by jiachen9393** [VeloCloud/website-ui#50]
## Issue Type

- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

![image](https://cloud.githubusercontent.com/assets/19999647/25294777/ce1c6934-26ae-11e7-840c-2f3da7485fd2.png)

## Steps to reproduce

New user after registration's first name and last name is fixed as Vy.

**Comment by kz4** [comment]
Fixed in https://github.com/VeloCloud/website-ui/pull/58/commits/8297fc03e4e7ba47695dd0dafb9d538f44deab29
