### ISSUE TITLE
Files become folders after refreshing the page

### ISSUE THREAD

**Issue by kz4** [VeloCloud/website-ui#54]
![file become fol](https://cloud.githubusercontent.com/assets/15188104/25309117/5f621f04-2792-11e7-8fb3-13b99a29c4af.png)

When first uploaded, they are showing correctly as files, but once refreshing the page, they become folders. My guess is that they are empty, the default for empty is folder? These should also be deletable as well. Even better would be, if the upload failed, they shouldn't even be shown here

**Comment by kz4** [comment]
Some more info regarding this bug. Generally it means when the file fails to upload. There are many reasons, one reason is the user token expires, but you still uploaded, it looked successful, but actually failed

**Comment by kz4** [comment]
More info: it happens if you have spaces in the file name. For example: hello world.png won't work while hello_world.png will work

**Comment by bsherrill480** [comment]
We're no longer showing empty.
