### ISSUE TITLE
List file browser will go over limit

### ISSUE THREAD

**Issue by kz4** [VeloCloud/website-ui#55]
If we have many folders, it will just keep going down, maybe have a scroll bar?
![image](https://cloud.githubusercontent.com/assets/15188104/25311178/23fcb6c8-27c8-11e7-8862-ba85bc19b8ce.png)

**Comment by kz4** [comment]
another screenshot of this problem
<img width="549" alt="screen shot 2017-04-23 at 3 57 20 pm" src="https://cloud.githubusercontent.com/assets/15188104/25316937/96db4f22-283d-11e7-86ca-da6bc7d8f3b9.png">

**Comment by kz4** [comment]
Overall view
<img width="1355" alt="screen shot 2017-04-23 at 5 08 00 pm" src="https://cloud.githubusercontent.com/assets/15188104/25317533/76f34416-2848-11e7-86b4-eeae4beeb187.png">

**Comment by chtran14** [comment]
Fixed with scroll bar :)
