### ISSUE TITLE
Tooltip the same for different files

### ISSUE THREAD

**Issue by kz4** [VeloCloud/website-ui#56]
apple tooltip
<img width="529" alt="screen shot 2017-04-23 at 3 37 16 pm" src="https://cloud.githubusercontent.com/assets/15188104/25316790/e2c06c68-283a-11e7-8484-814a92fbddc1.png">
obscure tooltip
<img width="513" alt="screen shot 2017-04-23 at 3 37 26 pm" src="https://cloud.githubusercontent.com/assets/15188104/25316797/ed1287d2-283a-11e7-9472-d02da21e2551.png">

**Comment by bsherrill480** [comment]
I remember seeing the fix for this. You're anchor tag isn't pointing to the right tooltip. See http://wwayne.com/react-tooltip/ for examples

**Comment by chtran14** [comment]
Or we can just remove the tooltip as it does not really provide much helpful info for the scientist. We have a file metadata/container already. If anyone wants to keep this, whoever in charge of making it can follow the guideline that Brian posted to fix it :)

**Comment by chtran14** [comment]
Final decision is to remove the tooltip completely based on issues 72 from the velo api github. I will close this one for now.
