### ISSUE TITLE
Profile page styling looks a little off

### ISSUE THREAD

**Issue by jgartman** [VeloCloud/website-ui#59]
Here's what the profile page looks like after I created and account and logged in for the first time: 

![image](https://cloud.githubusercontent.com/assets/12043806/25356146/3c51f59a-2907-11e7-8c53-14546f418139.png)

**Comment by chtran14** [comment]
You need to close the inspect section on the right. Since this is built for most scientists to use, they would not click on inspect like us as the col style is maximize for profile with 100% screen size. Thanks :)
