### ISSUE TITLE
Profile page contains data from another user

### ISSUE THREAD

**Issue by jgartman** [VeloCloud/website-ui#61]
I was logged into an account for a user that had a firstname and lastname saved.  I logged out and logged into an account where the user does not have a firstname or lastname saved but the previous users info was populated into those fields.  In the screenshots below user hsojnamtrag does not have firstname or lastname in dynamo but those fields were populated with old data from the previously logged in user.
![image](https://cloud.githubusercontent.com/assets/12043806/25357177/dfc86008-290a-11e7-9214-f0ca083bd8d7.png)

![image](https://cloud.githubusercontent.com/assets/12043806/25357185/e6718f92-290a-11e7-99e4-3bb9b2c7bcfa.png)

**Comment by nguyenvyl** [comment]
Hmm, I reckon the UI needs to clear out the store (which contains the user's profile info) on page load. I'll work on it.
